### ISSUE TITLE
Regarding possibly outdated dependency

### ISSUE THREAD

**Issue by jongmin1** [chiragnagpal/deep_cox_mixtures#1]
Hi, 
It seems like the current version of dsm (link: https://github.com/autonlab/DeepSurvivalMachines) does not work well with dcm. Could you please specify which version of dsm you've used for development?

**Comment by chiragnagpal** [comment]
Hi @jongmin1 the current version of the code doesn't require `dsm` (Unless you want to use `dsm` as a baseline model.) Let me know if it works for you now.

**Comment by jongmin1** [comment]
Your example works now! Thank you for letting me know :)

**Comment by chiragnagpal** [comment]
@jongmin1 Glad it worked out ! Let me know how it goes !
