### ISSUE TITLE
Could you add instructions on installation and utilization?

### ISSUE THREAD

**Issue by flippercy** [chiragnagpal/deep_cox_mixtures#2]
Hi @chiragnagpal:

Could you add some instructions and examples on how to install and use DCM, please? The paper reads great and I want to test the algorithm.

Thank you!

**Comment by chiragnagpal** [comment]
@flippercy  Thanks for checking it out -- I'll be adding an example notebook and all in the next couple of weeks to make it easy to test it out. In the mean time I'd also plug this https://autonlab.github.io/DeepSurvivalMachines/ its documented and easy to use and might be worth trying out..

**Comment by flippercy** [comment]
@chiragnagpal Thank you for the quick turnaround! Would be great if you could also add directions on how to install the library.

Best,

**Comment by flippercy** [comment]
Hi @chiragnagpal:

Thank you very much for adding the new stuff! However, there is no file named 'requirements.txt' in the repository and the installation returned an error message. Could you look into it, please? Did I misunderstand anything?

Thank you.

**Comment by chiragnagpal** [comment]
@flippercy Hi ! I have added some more details on how to use the model. Check this notebook https://nbviewer.jupyter.org/github/chiragnagpal/deep_cox_mixtures/blob/master/DCM%20on%20SUPPORT%20Dataset.ipynb

For installation all you need is tensorflow and you can run by cloning the repo. Let me know if that works.

**Comment by flippercy** [comment]
Thank you but there is no file named 'requirements.txt' in the repo; as a result, I got an error when running 
'pip install -r requirements.txt' as in the instruction.

Do I need to run this command to complete the installation?

Thank you.

**Comment by chiragnagpal** [comment]
@flippercy Nope -- you should be able to run with:
```
git clone https://github.com/chiragnagpal/deep_cox_mixtures
```

**Comment by flippercy** [comment]
Got it. Thank you!

**Comment by flippercy** [comment]
@chiragnagpal 

!git clone https://github.com/chiragnagpal/deep_cox_mixtures

from dcm import deep_cox_mixture

Cloning into 'deep_cox_mixtures'...
remote: Enumerating objects: 129, done.
remote: Counting objects: 100% (129/129), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 129 (delta 63), reused 64 (delta 23), pack-reused 0
Receiving objects: 100% (129/129), 910.78 KiB | 0 bytes/s, done.
Resolving deltas: 100% (63/63), done.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-93c8909d6cf1> in <module>
      1 get_ipython().system('git clone https://github.com/chiragnagpal/deep_cox_mixtures')
      2 
----> 3 from dcm import deep_cox_mixture

ModuleNotFoundError: No module named 'dcm'

What did I do wrong, please?

Thank you.

**Comment by chiragnagpal** [comment]
you'll have to cd into the repo and run the code from there...

**Comment by chiragnagpal** [comment]
try running the example notebook

**Comment by flippercy** [comment]
Thank you very much for the help! It works now.

Best,
