### ISSUE TITLE
Can DCM be used with time-dependent covariates?

### ISSUE THREAD

**Issue by flippercy** [chiragnagpal/deep_cox_mixtures#3]
Hi @chiragnagpal:

I am wondering whether DCM can be used with time-dependent covariates; such as in the data below:

![image](https://user-images.githubusercontent.com/51969693/134381293-06672c31-4bff-490a-b8ee-dc1da912e0fa.png)

Moreover, is there anyway to pull the coefficients of variables in the model like traditional cox models?

Thank you.

**Comment by flippercy** [comment]
@chiragnagpal: I just figured out that in the original paper you mentioned that so far the algorithm only worked with static datasets. Problem solved.

Moreover, could you let me know how to pull the parameters learned by the model, such as theta mentioned in the paper?

Thank you.

**Comment by chiragnagpal** [comment]
Hi @flippercy you can use DCM with Time-Dependent covariates by assuming the time varying covariates to be static
