### ISSUE TITLE
Error: 'ValueError: probabilities contain NaN'

### ISSUE THREAD

**Issue by flippercy** [chiragnagpal/deep_cox_mixtures#4]
Hi @chiragnagpal:

A couple of extra questions on DCM:

1. What is the definition of h and how to determine the best value of k and h?
2. I got an error with my internal data:

k = 3
h = 100
from dcm import dcm_tf as dcm
model = dcm.DeepCoxMixture(k, h)
 
model, losses = dcm.train(model, 
                  data_dev_X, data_dev_t, data_dev_y, 
                  data_val_X, data_val_t, data_val_y, 
                  epochs=10, lr=0.001, bs=128, 
                  use_posteriors=False,
                  random_state=19850606,
                  return_losses=True,
                  patience=3) 

Error: 'ValueError: probabilities contain NaN'

It happened at about the 10th epoch. How to fix it, please?

Thanks a lot!

**Comment by chiragnagpal** [comment]
would you be more comfortable with a pytorch implementation, I have one which is more stable than the current tensorflow one which I can share with you.

**Comment by flippercy** [comment]
Yes I do. Could you share it if stability is the root cause of the issue?

In addition, would you like to give me some insights on my question on k and h, please?

Best,

**Comment by flippercy** [comment]
Hi @chiragnagpal:

Could you share the new version of DCM with me, please? Is the size of the library small enough to be attached to an email?

Thank you.

**Comment by chiragnagpal** [comment]
Hi, would you be able to send me an email at <chiragn@cs.cmu.edu>?

**Comment by flippercy** [comment]
@chiragnagpal: an email has been sent yesterday.

Thank you.

**Comment by flippercy** [comment]
Hi @chiragnagpal:

Any updates, please?

Thank you.

**Comment by flippercy** [comment]
Hi @chiragnagpal:

Any updates, please?

Thank you.

**Comment by chiragnagpal** [comment]
Hi @flippercy Please check: https://autonlab.github.io/DeepSurvivalMachines/contrib
